services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'easy-whatsapp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - easy-db:/var/lib/mysql

volumes:
  easy-db: