services:
  postgres:
    container_name: postgres_easy_whatsapp_api
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - easy-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usr_easy_whatsapp_api
      - POSTGRES_PASSWORD=easy_whatsapp_api
      - POSTGRES_DB=easy-whatsapp

volumes:
  easy-db: